### ISSUE TITLE
<class 'pydub.exceptions.CouldntEncodeError'> occured when cherulize handling message

### ISSUE THREAD

**Issue by dfmjndm** [SonderXiaoming/cherugo#1]
[2022-07-26 13:02:10,008 pcr-cherugo] INFO: Message 1585141953 triggered cherulize.
[2022-07-26 13:02:10,055 pcr-cherugo] ERROR: <class 'pydub.exceptions.CouldntEncodeError'> occured when cherulize handling message 1585141953.
[2022-07-26 13:02:10,055 pcr-cherugo] ERROR: Encoding failed. ffmpeg/avlib returned error code: 1

Command:['ffmpeg', '-y', '-f', 'wav', '-i', '/tmp/tmpsq3pdlup', '-f', 'mp3', '/tmp/tmpt_qc_6ff']

Output from ffmpeg/avlib:

ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8 (GCC)
  configuration: --prefix=/usr/local/ffmpeg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from '/tmp/tmpsq3pdlup':
  Duration: 00:00:07.30, bitrate: 1536 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, stereo, s16, 1536 kb/s
Automatic encoder selection failed for output stream #0:0. Default encoder for format mp3 (codec mp3) is probably disabled. Please choose an encoder manually.
Error selecting an encoder for stream 0:0
Traceback (most recent call last):
  File "/hobot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/hobot/hoshino/modules/cherugo/cherugo.py", line 117, in cherulize
    voice = await chueru2voice(text[5:])
  File "/hobot/hoshino/modules/cherugo/cherugo.py", line 106, in chueru2voice
    outmp3.export(save_path, format="mp3")
  File "/usr/local/lib/python3.9/site-packages/pydub/audio_segment.py", line 970, in export
    raise CouldntEncodeError(
pydub.exceptions.CouldntEncodeError: Encoding failed. ffmpeg/avlib returned error code: 1

Command:['ffmpeg', '-y', '-f', 'wav', '-i', '/tmp/tmpsq3pdlup', '-f', 'mp3', '/tmp/tmpt_qc_6ff']

Output from ffmpeg/avlib:

ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8 (GCC)
  configuration: --prefix=/usr/local/ffmpeg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from '/tmp/tmpsq3pdlup':
  Duration: 00:00:07.30, bitrate: 1536 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, stereo, s16, 1536 kb/s
Automatic encoder selection failed for output stream #0:0. Default encoder for format mp3 (codec mp3) is probably disabled. Please choose an encoder manually.
Error selecting an encoder for stream 0:0

**Comment by SonderXiaoming** [comment]
寄，我没见过这个问题，复现不出来。
好像是Linux会出现的问题，我用的是windows
我看了一下网上解决方法，你可以试一把
把from_mp3改成from_file

**Comment by SonderXiaoming** [comment]
或者改成from_file_using_temporary_files或重装ffmpeg
不行就等大佬吧

**Comment by dfmjndm** [comment]
都不行

**Comment by SonderXiaoming** [comment]
方便提供一下运行环境（比如python版本，操作系统？）

**Comment by dfmjndm** [comment]
> 方便提供一下运行环境（比如python版本，操作系统？）

centos8，Python3.9

**Comment by SonderXiaoming** [comment]
你换个环境，比如windows什么的，也是这个报错嘛？
如果不是我有空装个centos8试一把

**Comment by SonderXiaoming** [comment]
> Default encoder for format mp3 (codec mp3) is probably disabled.

http://www.45fan.com/article.php?aid=20030135264781257277647837
参考这个网址试一把

**Comment by dfmjndm** [comment]
> > Default encoder for format mp3 (codec mp3) is probably disabled.
> 
> http://www.45fan.com/article.php?aid=20030135264781257277647837
> 参考这个网址试一把

"当前内容不存在!"

**Comment by SonderXiaoming** [comment]
> Default encoder for format mp3 (codec mp3) is probably disabled. Please choose an encoder manually.

https://blog.csdn.net/weixin_44736603/article/details/121537824
csdn总行吧

**Comment by SonderXiaoming** [comment]
应该是缺这个libmp3lame第三方库

**Comment by dfmjndm** [comment]
装完这个库，重装了ffmpeg，变成了这个报错

[2022-07-27 19:13:20,756 pcr-cherugo] INFO: Message -386656679 triggered cherulize.
[2022-07-27 19:13:22,438 pcr-cherugo] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when cherulize handling message -386656679.
[2022-07-27 19:13:22,440 pcr-cherugo] ERROR: <ActionFailed data=None, echo={'seq': 2}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>
Traceback (most recent call last):
  File "/hobot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/hobot/hoshino/modules/cherugo/cherugo.py", line 119, in cherulize
    await bot.send(ev, voice)
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/__init__.py", line 271, in send
    return await self.send_msg(**params)
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 38, in _handle_api_result
    raise ActionFailed(result=result)
aiocqhttp.exceptions.ActionFailed: <ActionFailed data=None, echo={'seq': 2}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording=' 请参考 go-cqhttp 端输出'>


看了一下res里面没有生成cherugo.mp3（路径和文件夹权限没问题）,所以gocq显示发送内容为空。
然后文字版的cherugo是发出来了，语音没有

**Comment by SonderXiaoming** [comment]
gocq报错看看

**Comment by dfmjndm** [comment]
> gocq报错看看

gocq显示发送的是空文件，res里面没生成cherugo.mp3
